#! /bin/dash
# ------------------------------------------------------------------------------
# apt-get-rootfs - Add apps to rootfs ad needed
#
# Must be run as root (use sudo of course!)
# ------------------------------------------------------------------------------

error_out () {
    echo "$1"
    exit 1
}

if [ "$(whoami)" != "root" ]; then
	error_out "Sorry, you are not root."
fi

export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true
export LC_ALL=C LANGUAGE=C LANG=C

# ------------------------------------------------------------------------------
# See if we can do anything at all - like apt-get install

cd ../ev3dev-rootfs

    echo    "-------------------------------------------------------------------------------"
    echo    " Installing additional apps as needed"
    echo    ""
    echo -n "    Type \"Yes\" to continue, anything else to skip ... "
    read YesNo

    if [ "${YesNo}" = "Yes" ]; then
    
        chroot ev3-rootfs apt-get update
        chroot ev3-rootfs apt-get install nfs-common
        chroot ev3-rootfs apt-get install samba-common

        echo    "Done"
        echo    "-------------------------------------------------------------------------------"
    fi

cd ${OLDPWD}


echo "-------------------------------------------------------------------------------"
exit
